<?php
$connector_name=  Mage::getModel('ren/client')->setConnectorName();
$connectorname=strtolower($connector_name);
?>
<!-- BEGIN Connectors Renren Connect -->

<script type="text/javascript">
//<![CDATA[
        document.observe('click', function(e){

	var target = e.findElement('a[rel^=connect_Renren]') || e.findElement('button[rel^=connect_Renren]');
	if (target && target.readAttribute('rel')=='connect_Renren') {

		var identityid = target.readAttribute('name');		
		window.open('<?php echo Mage::getModel('ren/client')->getConnectorUrl($connectorname,'/index'); ?>'+'?mid='+identityid,'mywindow','width=500,height=400');
		
	}
	var target = e.findElement('a[rel^=disconnect_Renren]') || e.findElement('button[rel^=disconnect_Renren]');
	if (target && target.readAttribute('rel')=='disconnect_Renren') {

		var identityid = target.readAttribute('name');		
		setLocation('<?php echo Mage::getModel('ren/client')->getConnectorUrl($connectorname,'/index'); ?>'+'?data=true&mid='+identityid);
		
	}
});
//]]>
</script>